spring:
  h2:
    console:
      enabled: true
#  init:
#    mode: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/practicebook
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true
logging:
  level:
    me.silvernine: DEBUG
jwt:
  header: Authorizaion
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # ?? ?? ???? base64? ??????
  token-validity-in-seconds: 86400