server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security
    driver-class-name: org.mariadb.jdbc.Driver
    username: ukha
    password: 1234

  main:
    allow-bean-definition-overriding: true

  #  mvc: --> WebMvcConfig ?? ???
#    view:
#      prefix: /templates/
#      suffix: .mustache
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 757699063028-lb8slrb5m7380in7ssud05hjeu5aggaq.apps.googleusercontent.com
            client-secret: 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
            scope: # 받고자 하는 데이터
              - email
              - profile
          facebook:
            client-id: 744759020732838
            client-secret: 4a5c0fb4c6173f1a3a0c9304da343c51
            scope:
              - email
              - public_profile # 페이스북 엑세스토큰 문서에 있음
          naver:
            client-id: IJeGVG64WPSpp2KL7V52
            client-secret: Ugdl_6EHvs
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
